### ISSUE TITLE
Build not working.

### ISSUE THREAD

**Issue by ghost** [echidnas/DankOS#3]
I am trying to build DankOS but the img size is only 2KB and it gets stuck at booting in VirtualBox

**Comment by wubbalubbadubdubonline** [comment]
the current commit builds for me and is 1.5MB in size, it sounds like perhaps the mounting stage failed for you. could you try running through that part manually and giving us the output?

**Comment by ghost** [comment]
@jmbaron it would be useful if you gave us some more info, like which os you used, what output you received and so on.
