### ISSUE TITLE
C functions don't work

### ISSUE THREAD

**Issue by DeclanHoare** [echidnas/DankOS#5]
This test program:

```
void testfun();
void testfun2(int value);

#include "dankos.h"

int _start()
{
	os_print_string_i("Hello from _start()!\n");
	testfun();
	testfun2(15);
	testfun();
	testfun();
	testfun();
	os_print_string_i("Goodbye from _start()!\n");
	return 0;
}

void testfun()
{
	os_print_string_i("Hello from testfun()!\n");
	return;
}

void testfun2(int value)
{
	for (int i = 0; i < value; i++)
	{
		os_print_string_i("Hello from testfun2()!\n");
	}
	return;
}
```

should obviously output

> Hello from _start()!
> Hello from testfun()!
> Hello from testfun2()!
> Hello from testfun2()!
> Hello from testfun2()!
> Hello from testfun2()!
> Hello from testfun2()!
> Hello from testfun2()!
> Hello from testfun2()!
> Hello from testfun2()!
> Hello from testfun2()!
> Hello from testfun2()!
> Hello from testfun2()!
> Hello from testfun2()!
> Hello from testfun2()!
> Hello from testfun2()!
> Hello from testfun2()!
> Hello from testfun()!
> Hello from testfun()!
> Hello from testfun()!
> Goodbye from _start()!

but the actual output is just

> Hello from _start()!

Not including the "return" statements on the void functions results in a kernel crash:

```
Kernel: The root process has been terminated,
	process exit code: 4294967295
	The kernel will now reload 'shell.bin'.
	Press a key to continue...
```

which is printed again when pressing a key.

**Comment by ghost** [comment]
Thanks for the feedback, we already know about this issue, and we think that it is related to GCC's (and linker's) inability to properly handle 16-bit code. We'll try to fix the problem somehow, else we'll have to start running programs inside of a 32-bit protected mode environment, and that should be interesting.
